# GitHub Pages configuration
title: eVidya Learning Platform
description: An interactive learning platform with courses, videos, and quizzes
baseurl: "/eVidya"
url: ""

# Build settings
markdown: kramdown
exclude:
    - .github/
    - README.md
    - LICENSE
